// vue/src/components/auth-components/Login.vue
<template>
    <div class="login_container">
        <el-form :model="loginForm" :rules="rules" ref="loginForm"
                 label-width="100px" class="login-form">
            <el-form-item label="用户名/邮箱" prop="username">
                <el-input v-model="loginForm.username" placeholder="请输入用户名或邮箱"></el-input>
            </el-form-item>
            <el-form-item label="密码" prop="password">
                <el-input v-model="loginForm.password" placeholder="请输入密码"
                          id="password" name="password" show-password></el-input>
            </el-form-item>
            <el-form-item>
                <el-button type="primary" @click="submitForm('loginForm')">登录</el-button>
            </el-form-item>
        </el-form>
    </div>
</template>

<script>

    export default {
        name: "Login",
        data() {
            return {
                loginForm: {
                    username: '',
                    password: ''
                },
                rules: {
                    username: [
                        {required: true, message: '请输入用户名或邮箱', trigger: 'blur'}
                    ],
                    password: [
                        {required: true, message: '请输入密码', trigger: 'blur'}
                    ]
                }
            }
        },
        methods: {
            submitForm(formName) {
                this.$refs[formName].validate((valid) => {
                    if (valid) {
                        let form = this.$data.loginForm;
                        this.$store.dispatch('auth/sendLogin', {
                                "username": form.username,
                                "password": form.password
                            }
                        )
                            .then(() => {
                                // 重定向到之前的页面
                                console.debug(this.$route.query.redirect);
                                if (this.$route.query.redirect) {
                                    this.$router.push(decodeURI(this.$route.query.redirect));
                                } else {
                                    this.$router.push('/home');
                                }
                            })
                            .catch(error =>
                                this.$message.error(
                                    '登陆失败: ' + error.msg ? error.msg : '连接服务器错误'
                                ))
                    } else {
                        this.$message.error('submit failed.');
                        return false;
                    }
                })
            }
        }
    }
</script>

<style scoped>
    .login_container {
        margin: 28px 25%;
    }
</style>

// angular/src/app/auth/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService, AuthenticationRequest } from "../../service/auth.service";
import { BaseResponse } from "../../class/base-response";
import {Router} from "@angular/router";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  errorMsg: string;
  request: AuthenticationRequest;

  constructor(
    private authService: AuthService,
    private router: Router
  ) {
    this.request = new AuthenticationRequest();
  }

  ngOnInit() {}
  login() {
    this.authService.sendLogin(this.request)
      .subscribe(
      resp => {
        console.log(JSON.stringify(resp));
        this.authService.saveToken(resp.data['token']);
        this.router.navigateByUrl('home');
      },
        error => {
        console.error(error);
        this.errorMsg = error || '未知错误';
        }
    );
  }

}

<div class="login_container">
  <form (ngSubmit)="login()" #loginForm="ngForm">
    <mat-form-field>
      <input matInput placeholder="用户名/邮箱" id="username" required
             [(ngModel)]="request.username" name="username">
    </mat-form-field>
    <mat-form-field>
      <mat-label>密码</mat-label>
      <input matInput type="password" id="password" required
             [(ngModel)]="request.password" name="password">
    </mat-form-field>

    <button mat-button color="primary" type="submit"
            [disabled]="!loginForm.form.valid">
      登录
    </button>

    <mat-error *ngIf="errorMsg">
      {{errorMsg}}
    </mat-error>
  </form>
</div>
